name: ManagerPlugin
version: '1.1.1'
main: me.tim.managerplugin.ManagerPlugin
authors: [ Timthegoathekingtheawesomethesigmatheeveythingpleasegivehimdiamondsandstuffbecauseheisatuffguypleasealfredpleasealsointeljjinowthinksthisisatypoanditsveryannoyingandthisisallwritteninonelinesonowitsrellylongandreallyannoyingtoaddstufftothepluginymlsectionsopleasegivemediamondswhenyoureadthisorgetaitocheckitimoutofthingstomakethislongerbuticankeepjustsayingrandomstuffiguessfortheloveofthegameyeiguessthatsreallyitjustgivemediamondsorsmthplease]
api-version: '1.21.11'
description: yes
load: POSTWORLD
